version: 0.2
phases:
  install:
    runtime-versions:
      golang: 1.x
  build:
    commands:
      - echo "Building Lambda function..."
      - go build -o bootstrap main.go
      # Create the appspec.yml for CodeDeploy
      - |
        cat << EOF > appspec.yaml
        version: 0.0
        Resources:
          - myFunction:
              Type: AWS::Lambda::Function
              Properties:
                Name: "${LAMBDA_FUNCTION_NAME}"
                Alias: "Live"
                CurrentVersion: "\${CurrentVersion}"
                TargetVersion: "\${TargetVersion}"
        Hooks:
          BeforeAllowTraffic: "${PreTrafficHookArn}"
          AfterAllowTraffic: "${PostTrafficHookArn}"
        EOF
      # Create CloudFormation template
      - |
        cat << EOF > template.yaml
        AWSTemplateFormatVersion: '2010-09-09'
        Resources:
          LambdaFunction:
            Type: 'AWS::Lambda::Function'
            Properties:
              FunctionName: ${LAMBDA_FUNCTION_NAME}
              Code:
                S3Bucket: ${ARTIFACT_BUCKET}
                S3Key: ${ARTIFACT_KEY}
              Runtime: provided.al2
              Handler: bootstrap
              Role: ${LAMBDA_ROLE_ARN}
          
          LambdaVersion:
            Type: 'AWS::Lambda::Version'
            Properties:
              FunctionName: !Ref LambdaFunction
          
          LambdaAlias:
            Type: 'AWS::Lambda::Alias'
            Properties:
              FunctionName: !Ref LambdaFunction
              Name: Live
              FunctionVersion: !GetAtt LambdaVersion.Version
        EOF

artifacts:
  files:
    - bootstrap
    - appspec.yaml
    - template.yaml
  discard-paths: no