
name: Go

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.23' ]

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache-dependency-path: subdir/go.sum
          
      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./...

      - name: Debug GitHub directory
        run: ls -R

      # Setup AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActions
          aws-region: us-east-1
          
      - name: Verify AWS Credentials 
        run: aws sts get-caller-identity

      # Load .env file 
      - name: Load .env variables 
        run: cat ../../bin/.env >> $GITHUB_ENV

      # CDK Build
      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: CDK Synth
        run: cdk synth --app "go run bin/cdk.go"
        env:
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          ACCOUNT_REGION: ${{ env.ACCOUNT_REGION }}
          GITHUB_OWNER: ${{ env.GITHUB_OWNER }}
          GITHUB_REPO: ${{ env.GITHUB_REPO }}
          METRIC_NAME: ${{ env.METRIC_NAME }}
          METRIC_NAMESPACE: ${{ env.METRIC_NAMESPACE }}
      
      # Optionally Deploy CDK Stack
      - name: CDK Deploy
        run: cdk deploy --require-approval never

      # Trigger AWS CodeBuild for Lambda Build
      - name: Trigger AWS CodeBuild
        run: aws codebuild start-build --project-name "CodeBuildV1"
